name: tanzu-deploy-workflow
on: [push]
jobs:
  tanzu_deploy_job:
    runs-on: ubuntu-latest
    permissions: write-all
    name: Build Cntainer Image on Commit
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy application to Tanzu Platform
        uses: tanzu-build/tanzu-build-action@v1.4
        with:
          container_registry: ghcr.io/${{ github.actor }}/<<ENTER VALUE>>
          buildPlanSource: './platform-config.yaml'
          javaVersion: 17
